### PR TITLE
Use Selenide instead oа Selenium webdriver - make tests much more clean

### PR DESCRIPTION
**Pull request by asolntsev**
Hi Thomas!
I am Andrei Solntsev, we talked to you about BDD ("bullshit driven development") in Kiev last weekend.

I attended to your speech, thank you for promoting clean code.

Are you familiar with Selenide? It's a testing library on top of Selenium that makes tests much more clean. I am submitting this pull request to demonstrate you the difference.

### CODE REVIEW

**Comment by tsundberg** [comment]
Hi!

On 2 March 2015 at 00:59, Andrei Solntsev notifications@github.com wrote:

> Hi Thomas!
> I am Andrei Solntsev, we talked to you about BDD ("bullshit driven development") in Kiev last weekend.

I do remeber. I would have wanted to see you presentation, the subject
was interesting. My skills in Russian prevented me somewhat...

> I attended to your speech, thank you for promoting clean code.

Clean code was the most important point I wanted to convey.

> Are you familiar with Selenide? It's a testing library on top of Selenium that makes tests much more clean. I am submitting this pull request to demonstrate you the difference.

Nope, I am not familiar with it. I looked at you pull request and it
looks interesting. I am, however, not willing to merge the pull
request to that particular branch since it is the result of the
presentation.

I am thinking of creating a new branch based on the tip from the
presentation. I would be willing to accept a pull request to that
branch.

Let me get back to you with a new branch name when it is ready.

/Thomas

> ---
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/tsundberg/Selenium-and-the-Four-Rules-of-Simple-Design/pull/1
> 
> Commit Summary
> 
> Use Selenide instead of pure Selenium webdriver - make tests much more clean
> 
> File Changes
> 
> M pom.xml (5)
> M src/test/java/se/thinkcode/AddGeekyStuffToCartTest.java (20)
> M src/test/java/se/thinkcode/CartPage.java (36)
> M src/test/java/se/thinkcode/ThinkGeekHelper.java (58)
> 
> Patch Links:
> 
> https://github.com/tsundberg/Selenium-and-the-Four-Rules-of-Simple-Design/pull/1.patch
> https://github.com/tsundberg/Selenium-and-the-Four-Rules-of-Simple-Design/pull/1.diff
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Thomas Sundberg
M. Sc. in Computer Science

Mobile: +46 70 767 33 15
Blog: http://thomassundberg.wordpress.com/
Twitter: @thomassundberg

Better software through faster feedback

**Comment by asolntsev** [comment]
Sure, waiting for your new branch.

Sent from my HTC

----- Reply message -----

**Comment by tsundberg** [comment]
Hi Andrei!

On 3 March 2015 at 19:58, Andrei Solntsev notifications@github.com wrote:

> Sure, waiting for your new branch.

Here it is: https://github.com/tsundberg/Selenium-and-the-Four-Rules-of-Simple-Design/tree/Selenide-example

Cheers!
Thomas

> Sent from my HTC
> 
> ----- Reply message -----
> From: "Thomas Sundberg" notifications@github.com
> To: "tsundberg/Selenium-and-the-Four-Rules-of-Simple-Design" Selenium-and-the-Four-Rules-of-Simple-Design@noreply.github.com
> Cc: "Andrei Solntsev" andrei.solntsev@gmail.com
> Subject: [Selenium-and-the-Four-Rules-of-Simple-Design] Use Selenide instead oа Selenium webdriver - make tests much more clean (#1)
> Date: Mon, Mar 2, 2015 12:43
> 
> Hi!
> 
> On 2 March 2015 at 00:59, Andrei Solntsev notifications@github.com wrote:
> 
> > Hi Thomas!
> > 
> > I am Andrei Solntsev, we talked to you about BDD ("bullshit driven development") in Kiev last weekend.
> 
> I do remeber. I would have wanted to see you presentation, the subject
> 
> was interesting. My skills in Russian prevented me somewhat...
> 
> > I attended to your speech, thank you for promoting clean code.
> 
> Clean code was the most important point I wanted to convey.
> 
> > Are you familiar with Selenide? It's a testing library on top of Selenium that makes tests much more clean. I am submitting this pull request to demonstrate you the difference.
> 
> Nope, I am not familiar with it. I looked at you pull request and it
> 
> looks interesting. I am, however, not willing to merge the pull
> 
> request to that particular branch since it is the result of the
> 
> presentation.
> 
> I am thinking of creating a new branch based on the tip from the
> 
> presentation. I would be willing to accept a pull request to that
> 
> branch.
> 
> Let me get back to you with a new branch name when it is ready.
> 
> /Thomas
> 
> > ---
> > 
> > You can view, comment on, or merge this pull request online at:
> > 
> > https://github.com/tsundberg/Selenium-and-the-Four-Rules-of-Simple-Design/pull/1
> > 
> > Commit Summary
> > 
> > Use Selenide instead of pure Selenium webdriver - make tests much more clean
> > 
> > File Changes
> > 
> > M pom.xml (5)
> > 
> > M src/test/java/se/thinkcode/AddGeekyStuffToCartTest.java (20)
> > 
> > M src/test/java/se/thinkcode/CartPage.java (36)
> > 
> > M src/test/java/se/thinkcode/ThinkGeekHelper.java (58)
> > 
> > Patch Links:
> > 
> > https://github.com/tsundberg/Selenium-and-the-Four-Rules-of-Simple-Design/pull/1.patch
> > 
> > https://github.com/tsundberg/Selenium-and-the-Four-Rules-of-Simple-Design/pull/1.diff
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> Thomas Sundberg
> 
> M. Sc. in Computer Science
> 
> Mobile: +46 70 767 33 15
> 
> Blog: http://thomassundberg.wordpress.com/
> 
> Twitter: @thomassundberg
> 
> Better software through faster feedback
> 
> &mdash;
> 
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Thomas Sundberg
M. Sc. in Computer Science

Mobile: +46 70 767 33 15
Blog: http://thomassundberg.wordpress.com/
Twitter: @thomassundberg

Better software through faster feedback

**Comment by asolntsev** [comment]
Thank you!
I have submitted my pull request.

Andrei Solntsev

2015-03-03 22:41 GMT+02:00 Thomas Sundberg notifications@github.com:

**Pull request closed without merging**
